name: pine
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: use checkout@v2 action
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: pine install
        run: mvn clean install
      - name: pine test case result
        run: mvn test
      - name: report the result of code coverage
        run: bash <(curl -s https://codecov.io/bash)


